export function renderHome({ head, header, footer, card, categories, tools }) {
  const popular = tools.slice(0, 6).map(card).join('');
  const groups = categories.map(category => {
    const items = tools.filter(tool => tool.category === category.id);
    const dateTime = category.id === 'date-time';
    return `<section class="category-group ${dateTime ? 'date-time-group' : ''}" id="category-${category.id}"><div class="category-heading"><span class="category-symbol">${category.icon}</span><div><h3>${category.name}</h3><p>${category.description}</p></div><span class="category-count">${items.length}개</span></div><div class="card-grid">${items.map(card).join('')}</div>${items.length > 4 ? `<button class="category-more" type="button" aria-expanded="false">${dateTime ? '날짜·시간' : category.name} 전체보기 <span aria-hidden="true">→</span></button>` : ''}</section>`;
  }).join('');
  return `${head('대한민국 토탈 계산기', '대출, 급여, 부동산, 환율, 날짜와 시간까지 한 곳에서 계산하세요.')}<body>${header}<main>
    <section class="hero"><div class="shell hero-grid"><div class="hero-content"><span class="eyebrow"><span class="status-dot"></span> 대한민국 토탈 계산기</span><h1>무엇을<br><em>계산할까요?</em></h1><p>생활 속 궁금한 숫자를 쉽고 빠르게 확인하세요.</p><form id="search-form" class="search-box" role="search"><label class="sr-only" for="site-search">계산기 검색</label><span aria-hidden="true">⌕</span><input id="site-search" type="search" placeholder="예: 3억 대출 30년" autocomplete="off"><button type="submit">검색</button></form><div class="quick-search"><span>이렇게 찾아보세요</span><button type="button" data-query="3억 대출 30년">3억 대출 30년</button><button type="button" data-query="8억 아파트 총비용">8억 아파트 총비용</button><button type="button" data-query="퇴직금">퇴직금</button><button type="button" data-query="100달러">100달러</button><button type="button" data-query="오늘부터 100일 후">오늘부터 100일 후</button></div></div><div class="hero-art" aria-hidden="true"><div class="art-glow"></div><div class="art-card art-card-main"><span class="art-kicker">대출 계산 예시 · 월 상환액</span><strong>1,467,052<span>원</span></strong><div class="art-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><span class="art-foot">내 숫자를 더 명확하게</span></div><div class="art-pill art-pill-top">✦ 간편한 계산</div><div class="art-pill art-pill-bottom">✓ 결과 바로 확인</div></div></div></section>
    <div class="shell"><section id="popular" class="section-block"><div class="section-heading"><div><span class="section-kicker">POPULAR TOOLS</span><h2>지금 가장 많이 찾는 계산기</h2><p>자주 쓰는 계산부터 바로 시작해 보세요.</p></div><a class="text-link" href="#all-tools">전체 보기 →</a></div><div class="card-grid popular-grid">${popular}</div></section>
    <section class="category-strip" aria-label="카테고리 바로가기">${categories.map(category => `<a href="#category-${category.id}"><span>${category.icon}</span><strong>${category.name}</strong><small>↗</small></a>`).join('')}</section>
    <section id="recent-tools" class="section-block recent-tools" hidden><div class="section-heading"><div><span class="section-kicker">RECENT</span><h2>최근 사용한 계산기</h2></div></div><div id="recent-list" class="card-grid"></div></section>
    <section id="all-tools" class="section-block all-tools"><div class="section-heading"><div><span class="section-kicker">ALL CALCULATORS</span><h2>카테고리별 계산기</h2><p>궁금한 주제에서 필요한 계산기를 골라 보세요.</p></div><span class="tool-count">총 ${tools.length}개의 계산기</span></div><p id="search-empty" class="empty-message" hidden>일치하는 계산기가 없습니다. 다른 단어로 검색해 보세요.</p>${groups}</section>
    <section class="trust-banner"><span class="trust-icon" aria-hidden="true">✳</span><div><strong>입력한 숫자는 브라우저에서 계산해요.</strong><p>계정 없이 바로 사용하고, 결과를 보고 값을 자유롭게 바꿔 보세요.</p></div></section></div></main>${footer}</body></html>`;
}
