import { generalCalculatorMarkup } from './general-page.js';

export function renderHome({ head, header, footer, card, categories, tools, siteUrl }) {
  const popular = tools.slice(0, 6).map(card).join('');
  const groups = categories.map(category => {
    const items = tools.filter(tool => tool.category === category.id);
    const dateTime = category.id === 'date-time';
    return `<section class="category-group ${dateTime ? 'date-time-group' : ''}" id="category-${category.id}"><div class="category-heading"><span class="category-symbol">${category.icon}</span><div><h3>${category.name}</h3><p>${category.description}</p></div><span class="category-count">${items.length}개</span></div><div class="card-grid">${items.map(card).join('')}</div>${items.length > 4 ? `<button class="category-more" type="button" aria-expanded="false">${dateTime ? '날짜·시간' : category.name} 전체보기 <span aria-hidden="true">→</span></button>` : ''}</section>`;
  }).join('');
  const siteSchema = { '@context': 'https://schema.org', '@type': 'WebSite', name: '계산해줘', alternateName: '계산기', url: `${siteUrl}/` };
  return `${head('무료 온라인 계산기', '무료 온라인 계산기부터 대출, 연봉 실수령액, 퇴직금, 부동산, 환율, 날짜 계산까지 한 곳에서 빠르게 계산하세요.', { home: true, schema: siteSchema })}<body>${header}<main>
    <section class="hero"><div class="shell hero-grid"><div class="hero-content"><span class="eyebrow"><span class="status-dot"></span> 계산해줘</span><h1>무료 온라인 <em>계산기</em></h1><p>대출·연봉·부동산·날짜·환율까지 필요한 계산을 한 곳에서</p><form id="search-form" class="search-box" role="search"><label class="sr-only" for="site-search">계산기 검색</label><span aria-hidden="true">⌕</span><input id="site-search" type="search" placeholder="대출, 연봉, 날짜, 환율, 일반 계산기 검색" autocomplete="off"><button type="submit">검색</button></form><div class="quick-search"><span>이렇게 찾아보세요</span><button type="button" data-query="3억 대출 30년">3억 대출 30년</button><button type="button" data-query="8억 아파트 총비용">8억 아파트 총비용</button><button type="button" data-query="퇴직금">퇴직금</button><button type="button" data-query="100달러">100달러</button><button type="button" data-query="오늘부터 100일 후">오늘부터 100일 후</button></div></div><div class="hero-art hero-calculator"><div class="hero-mini-title">바로 계산해 보세요 <a href="/calculator/">일반 계산기 열기 →</a></div>${generalCalculatorMarkup(true)}</div></div></section>
    <div class="shell"><section id="popular" class="section-block"><div class="section-heading"><div><span class="section-kicker">POPULAR TOOLS</span><h2>지금 가장 많이 찾는 계산기</h2><p>자주 쓰는 계산부터 바로 시작해 보세요.</p></div><a class="text-link" href="#all-tools">전체 보기 →</a></div><div class="card-grid popular-grid">${popular}</div></section>
    <section class="category-strip" aria-label="카테고리 바로가기">${categories.map(category => `<a href="#category-${category.id}"><span>${category.icon}</span><strong>${category.name}</strong><small>↗</small></a>`).join('')}</section>
    <section id="recent-tools" class="section-block recent-tools" hidden><div class="section-heading"><div><span class="section-kicker">RECENT</span><h2>최근 사용한 계산기</h2></div></div><div id="recent-list" class="card-grid"></div></section>
    <section id="all-tools" class="section-block all-tools"><div class="section-heading"><div><span class="section-kicker">ALL CALCULATORS</span><h2>카테고리별 계산기</h2><p>궁금한 주제에서 필요한 계산기를 골라 보세요.</p></div><span class="tool-count">총 ${tools.length}개의 계산기</span></div><p id="search-empty" class="empty-message" hidden>일치하는 계산기가 없습니다. 다른 단어로 검색해 보세요.</p>${groups}</section>
    <section class="home-explainer" aria-labelledby="home-explainer-title"><h2 id="home-explainer-title">필요한 계산을 한 곳에서</h2><p>간단한 사칙연산은 <a href="/calculator/">무료 온라인 계산기</a>에서 바로 처리할 수 있습니다. 대출과 적금은 금융 카테고리에서, 연봉 실수령액과 퇴직금은 직장·급여 카테고리에서 확인해 보세요. 부동산 구매 비용, 날짜 차이, 환율 계산도 각각의 계산기에 입력값을 넣으면 결과를 바로 볼 수 있습니다.</p><a href="#all-tools">모든 계산기 살펴보기 →</a></section>
    <section class="trust-banner"><span class="trust-icon" aria-hidden="true">✳</span><div><strong>입력한 숫자는 브라우저에서 계산해요.</strong><p>계정 없이 바로 사용하고, 결과를 보고 값을 자유롭게 바꿔 보세요.</p></div></section></div></main>${footer}</body></html>`;
}
